import os


MONGODB_URI = os.environ['MONGODB_URI']
MONGODB_METRICS_COLLECTION = os.environ['MONGODB_METRICS_COLLECTION']
MONGODB_CORRELATIONS_COLLECTION = os.environ['MONGODB_CORRELATIONS_COLLECTION']
