version: "3.9"

services:
  web:
    image: welltory
    command: uvicorn main:app --env-file .env --host 0.0.0.0 --reload
    volumes:
      - ./:/app
    ports:
      - "18000:8000"
      - "17000:7000"
    
  webcopy:
    image: welltory
    command: uvicorn main:app --env-file .env --host 0.0.0.0 --reload
    volumes:
      - ./:/app
    ports:
      - "18001:8000"
      - "17001:7000"

  calculator:
    image: mumtozvalijonov/welltory_calculator
    command: ["python", "calculator.py"]
    env_file:
      - .env

  mongo:
    image: "mongo"
    ports:
      - "27018:27017"

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.8.3-management
    env_file:
      - .env
    ports:
      - "5672:5672"  
      - "15672:15672" 

  load_balancer:
    image: nginx
    volumes:
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8080:8888"
    environment:
    - NGINX_PORT=8888