version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: web
    volumes:
      - ./:/app
    ports:
      - "18000:8000"
      - "17000:7000"

  calculator:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: calculator
    command: ["python", "calculator.py"]
    env_file:
      - .env

  mongo:
    image: "mongo"
    ports:
      - "27018:27017"

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.8.3-management
    env_file:
      - .env
    ports:
      - "5672:5672"  
      - "15672:15672" 
